version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development  # Optional, use if needed
  
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile-streamlit
    ports:
      - "8501:8501"
