# Dockerfile-flask

# Use official Python image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

# Copy the Flask app
COPY flask_api.py /app/

# Expose Flask port
EXPOSE 8080

# Command to run the Flask app
CMD ["python", "flask_api.py"]
